for ENV_VAR in "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" "CLERK_SECRET_KEY" "NEXT_PUBLIC_CLERK_SIGN_IN_URL" "NEXT_PUBLIC_CLERK_SIGN_UP_URL" "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL" "NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL" "DATABASE_URL" "GEMINI_API_KEY"; do
  val=$(grep "^${ENV_VAR}=" .env | cut -d '=' -f 2-)
  echo "$val" | npx vercel env add $ENV_VAR production
done
